name: test

on:
  push:
    branches:
      - develop
      
  workflow_dispatch:

jobs:
  deploy:        
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: echo
        run: echo "hello world develop"