name: test

on:
  push:
    branches: [main]
  pull_request:
    types: [closed]
    branches: [main]

  workflow_dispatch:

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.x]

    steps:      
      - name: echo
        run: echo "hello world"